import { Router } from "express";
import authRoutes from "./sub-routes/auth-routes";
import userRoutes from "./sub-routes/user-routes";
import microsoftRoutes from "./sub-routes/microsoft-routes";
import smartfloRoutes from "./sub-routes/smartflo-routes";
import whatsappRoutes from "./sub-routes/whatsapp-routes";
import integrationsRoutes from "./sub-routes/integrations-routes";
import leadRoutes from "./sub-routes/lead-routes";
import opportunityRoutes from "./sub-routes/opportunity-routes";
import activityRoutes from "./sub-routes/activity-routes";
import attendanceRoutes from "./sub-routes/attendance-routes";
import dashboardRoutes from "./sub-routes/dashboard-routes";
import geographyRoutes from "./sub-routes/geography-routes";
import salesTeamRoutes from "./sub-routes/sales-team-routes";
import levelRoutes from "./sub-routes/level-routes";
import officeRoutes from "./sub-routes/office-routes";
import targetRoutes from "./sub-routes/target-routes";
import incentivePlanRoutes from "./sub-routes/incentive-plan-routes";
import commissionRuleRoutes from "./sub-routes/commission-rule-routes";
import userIncentivePlanRoutes from "./sub-routes/user-incentive-plan-routes";
import structureAxisRoutes from "./sub-routes/structure-axis-routes";
import rolePermissionRoutes from "./sub-routes/role-permission-routes";
import userPermissionOverrideRoutes from "./sub-routes/user-permission-override-routes";
import managerChangeLogRoutes from "./sub-routes/manager-change-log-routes";
import approvalBandRoutes from "./sub-routes/approval-band-routes";
import classificationRoutes from "./sub-routes/classification-routes";
import scheduledTransferRoutes from "./sub-routes/scheduled-transfer-routes";
import delegationRoutes from "./sub-routes/delegation-routes";
import userCommissionRoutes from "./sub-routes/user-commission-routes";
import fofoOnboardingRoutes from "./sub-routes/fofo-onboarding-routes";
import reportRoutes from "./sub-routes/report-routes";
import leaveRoutes from "./sub-routes/leave-routes";
import expenseRoutes from "./sub-routes/expense-routes";
import messageTemplateRoutes from "./sub-routes/message-template-routes";
import pipelineStageRoutes from "./sub-routes/pipeline-stage-routes";
import leadCategoryRoutes from "./sub-routes/lead-category-routes";
import assignmentRuleRoutes from "./sub-routes/assignment-rule-routes";
import appSettingsRoutes from "./sub-routes/app-settings-routes";
import qrCampaignRoutes from "./sub-routes/qr-campaign-routes";
import publicQrRoutes from "./sub-routes/public-qr-routes";
import approvalsInboxRoutes from "./sub-routes/approvals-inbox-routes";
import auditConsentRoutes from "./sub-routes/audit-consent-routes";
import teamDashboardRoutes from "./sub-routes/team-dashboard-routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/integrations/microsoft", microsoftRoutes);
router.use("/integrations/smartflo", smartfloRoutes);
router.use("/integrations/whatsapp", whatsappRoutes);
router.use("/integrations", integrationsRoutes);
router.use("/leads", leadRoutes);
router.use("/opportunities", opportunityRoutes);
router.use("/activities", activityRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/geography", geographyRoutes);
router.use("/sales-teams", salesTeamRoutes);
router.use("/levels", levelRoutes);
router.use("/offices", officeRoutes);
router.use("/targets", targetRoutes);
router.use("/incentive-plans", incentivePlanRoutes);
router.use("/commission-rules", commissionRuleRoutes);
router.use("/user-incentive-plans", userIncentivePlanRoutes);
router.use("/structure-axes", structureAxisRoutes);
router.use("/role-permissions", rolePermissionRoutes);
router.use("/user-permission-overrides", userPermissionOverrideRoutes);
router.use("/manager-change-log", managerChangeLogRoutes);
router.use("/approval-bands", approvalBandRoutes);
router.use("/classification", classificationRoutes);
router.use("/scheduled-transfers", scheduledTransferRoutes);
router.use("/delegations", delegationRoutes);
router.use("/user-commissions", userCommissionRoutes);
router.use("/fofo-onboarding", fofoOnboardingRoutes);
router.use("/reports", reportRoutes);
router.use("/leave", leaveRoutes);
router.use("/expenses", expenseRoutes);
router.use("/message-templates", messageTemplateRoutes);
router.use("/pipeline-stages", pipelineStageRoutes);
router.use("/lead-categories", leadCategoryRoutes);
router.use("/assignment-rules", assignmentRuleRoutes);
router.use("/app-settings", appSettingsRoutes);
router.use("/qr-campaigns", qrCampaignRoutes);
router.use("/public/qr", publicQrRoutes);
router.use("/approvals", approvalsInboxRoutes);
router.use("/audit-consent", auditConsentRoutes);
router.use("/team-dashboard", teamDashboardRoutes);

router.get("/health", (_req, res) => {
  res.json({ success: true, message: "FieldForce API is running" });
});

export default router;
